### ISSUE TITLE
favicon.ico

### ISSUE THREAD

**Issue by taeymma** [OnroerendErfgoed/atramhasisstijl#4]
Create a favicon based on the new atramhasis logo

**Comment by TOM-VC** [comment]
Een versie op 64x64 ipv 32x32 probeer eens aub?

Op 25-aug.-2015, om 15:40 heeft taeymma <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:

Create a favicon based on the new atramhasis logo

**Comment by cedrikv** [comment]
heb je voorbeeld icoontje?

**Comment by taeymma** [comment]
just getest, nog paar aanpassingen en dan zalk et ier zetten

**Comment by taeymma** [comment]
Unfortunately, we don’t support that file type. 

Dus ge zult ier es moete komen zien..
